# Simple CI para CajaPyme (GitHub Actions)
# Corre tests y lint en cada push/pull request

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cajapyme_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/cajapyme_test
      JWT_SECRET: testsecret
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Instalar dependencias backend
        run: |
          cd backend
          npm install
      - name: Instalar dependencias frontend
        run: |
          cd frontend
          npm install
      - name: Migrar base de datos
        run: |
          cd backend
          npx prisma migrate deploy
      - name: Ejecutar tests backend
        run: |
          cd backend
          npx jest --runInBand
      - name: Lint frontend
        run: |
          cd frontend
          npx eslint src --max-warnings=0
